#!/command/with-contenv sh

printf '0\n' > /run/s6-linux-init-container-results/exitcode

echo
echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] ====================================================="
echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO]              Shutting down gracefully..."
echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] ====================================================="
echo

/run/s6/basedir/bin/halt

exit 0
